### ISSUE TITLE
measure temp with 1 type of sensor

### ISSUE THREAD

**Issue by mr-eggleton** [UTCSheffield/PiTemp#1]

**Comment by 14keeblem** [comment]
Weather
Just like the light module, we can import the weather module by typing:
from envirophat import weather

To read the temperature in degrees Celsius, type the following:
print(weather.temperature())

**Comment by 14keeblem** [comment]
Configuration variables:
display_options (Optional) array: List of readings to monitor. Default is monitoring all of them: 
temperature: ambient temperature in Celsius. Since the sensor is close to the Raspberry Pi, that might affect the accuracy of the reading (ie. the Pi might heat up the sensor)
pressure: atmospheric pressure in hPa.
light: ambient light, as an integer in the 0-65535 range
light_red: red color reading scaled to the ambient light, as an integer in the 0-255 range
light_green: green color reading scaled to the ambient light, as an integer in the 0-255 range
light_blue: blue color reading scaled to the ambient light, as an integer in the 0-255 range
accelerometer_x: accelerometer reading in units of G, along the X axis
accelerometer_y: accelerometer reading in units of G, along the Y axis
accelerometer_z: accelerometer reading in units of G, along the Z axis
magnetometer_x: magnetometer reading, the X component of the raw vector
magnetometer_y: magnetometer reading, the Y component of the raw vector
magnetometer_z: magnetometer reading, the X component of the raw vector
voltage_0: voltage reading on Analog In 0 in units of V
voltage_1: voltage reading on Analog In 1 in units of V
voltage_2: voltage reading on Analog In 2 in units of V
voltage_3: voltage reading on Analog In 3 in units of V
use_led (Optional) True / False boolean; Default value is False, declaring that the on-board LEDs are not used for the color measurements thus these readings are based on the ambient light. If the value is set to True, the on-board LEDs will blink whenever a reading is taken.
